export const layoutTokens = {
    layout: {
        root: "flex flex-col min-h-screen"
    },
    auth: {
        defaultVariant: "split" as "split" | "centered",
        bgGradientCentered: "white",
        shapeColorCentered: "blue",
        bgGradientSplit: "bg-accent-default",
        shapeColorSplit: "#1f2937",
        containerCentered: "relative min-h-screen flex",
        containerSplit: "relative min-h-screen flex bg-background-secondary",
        backgroundCentered: "absolute inset-0",
        backgroundSplit: "absolute inset-0 hidden lg:block",
        formWrapperCentered: "absolute inset-0 flex justify-center items-center z-20",
        formInnerCentered: "w-full h-full flex justify-center items-center p-lg bg-transparent backdrop-blur-sm rounded-lg shadow-lg",
        formWrapperSplit: "flex flex-col flex-1 px-sm lg:px-none z-10",
        formInnerSplit: "flex-1 flex justify-center items-center",
        animatedRoute: "w-full flex justify-center items-center"
    },
    clientDashboard: {
        root: "min-h-screen bg-background-secondary-2",
        content: "flex flex-col flex-1"
    },
    designerDashboard: {
        root: "flex h-screen",
        sidebar: "hidden lg:block",
        drawerWidth: "w-64",
        content: "flex-1 flex flex-col overflow-hidden"
    },
    scraper: {
        // Root
        root: "min-h-screen bg-background-primary text-text-primary",

        // Welcome screen
        welcomeScreen: "min-h-screen flex items-center justify-center p-sm sm:p-md",
        welcomeInner: "text-center max-w-2xl space-y-lg sm:space-y-xl w-full",
        welcomeIconWrapper: "flex justify-center",
        welcomeIcon: "w-16 h-16 sm:w-20 sm:h-20 bg-gradient-to-br from-accent-default to-accent-hover rounded-xl sm:rounded-2xl flex items-center justify-center shadow-2xl",
        welcomeTextBlock: "space-y-sm",
        welcomeActions: "flex items-center gap-lg lg:gap-md justify-center flex-col lg:flex-row",
        welcomePrimaryBtn: "bg-gradient-to-r from-accent-default to-accent-hover text-accent-foreground px-lg py-md rounded-xl font-medium shadow-lg hover:shadow-xl flex items-center gap-sm text-para-lg will-change-transform",
        welcomeTasteRow: "flex items-center justify-center gap-sm",
        welcomeClearBtn: "text-accent-default hover:text-accent-hover underline text-para-sm",

        // Input screen
        inputScreen: "min-h-screen",
        inputGrid: "grid grid-cols-1 lg:grid-cols-2 min-h-screen",
        inputLeft: "bg-background-primary lg:border-r border-border-default p-md sm:p-lg flex flex-col justify-center",
        inputLeftInner: "max-w-xl mx-auto w-full space-y-lg sm:space-y-xl",
        inputBackBtn: "text-text-secondary hover:text-text-primary transition-colors flex items-center gap-sm text-para-sm",
        inputToggleWrapper: "flex items-center justify-center",
        inputToggleInner: "bg-background-secondary rounded-full p-1 flex",
        inputToggleBtnActive: "flex items-center justify-center gap-xs sm:gap-sm px-md sm:px-lg py-xs sm:py-sm rounded-full text-para-sm sm:text-para-md font-medium transition-all bg-accent-default text-accent-foreground shadow-lg",
        inputToggleBtnInactive: "flex items-center justify-center gap-xs sm:gap-sm px-md sm:px-lg py-xs sm:py-sm rounded-full text-para-sm sm:text-para-md font-medium transition-all text-text-secondary hover:text-text-primary",
        inputTextBlock: "text-center space-y-sm sm:space-y-md",
        inputFieldWrapper: "space-y-sm",
        inputFieldInner: "relative",
        inputField: "w-full px-md sm:px-lg py-sm sm:py-md bg-background-secondary border-2 border-border-default rounded-lg sm:rounded-xl text-text-primary placeholder:text-text-tertiary focus:outline-none focus:border-accent-default transition-all text-base sm:text-lg pr-12 sm:pr-14",
        inputSubmitBtn: "absolute right-2 top-1/2 -translate-y-1/2 bg-accent-default text-accent-foreground p-2 sm:p-3 rounded-lg hover:bg-accent-hover hover:shadow-lg transition-all",
        inputSuggestionsWrapper: "space-y-sm",
        inputSuggestionBtn: "px-sm sm:px-md py-xs sm:py-sm bg-background-secondary border border-border-default rounded-lg text-para-xs sm:text-para-sm text-text-primary hover:border-accent-default hover:bg-accent-subtle transition-all",
        inputRight: "bg-background-secondary flex-col gap-lg p-md sm:p-lg flex items-center justify-center min-h-[50vh] lg:min-h-full",
        inputRightIcon: "w-24 h-24 sm:w-32 sm:h-32 bg-gradient-to-br from-accent-default to-accent-hover rounded-full flex items-center justify-center mx-auto shadow-2xl",
        inputRightIconInner: "text-accent-foreground text-4xl sm:text-5xl",
        inputRightContent: "text-center space-y-md sm:space-y-lg max-w-lg",
        inputRightTextBlock: "space-y-sm",
        inputRightGrid: "grid grid-cols-1 sm:grid-cols-2 gap-sm sm:gap-md text-left",
        inputRightCard: "bg-background-primary rounded-lg sm:rounded-xl p-sm sm:p-md",

        // Processing screen
        processingScreen: "min-h-screen flex items-center justify-center p-sm sm:p-md",
        processingCard: "bg-background-primary-2 backdrop-blur-lg border-2 border-border-default rounded-2xl sm:rounded-3xl p-lg sm:p-xl shadow-md max-w-lg w-full",
        processingCardInner: "text-center space-y-lg sm:space-y-xl",
        processingSpinnerWrapper: "relative",
        processingSpinner: "w-20 h-20 sm:w-24 sm:h-24 border-4 border-border-muted border-t-accent-default rounded-full animate-spin mx-auto",
        processingSpinnerIcon: "absolute inset-0 flex items-center justify-center",
        processingTextBlock: "",
        processingStepRow: "flex items-center gap-sm sm:gap-md justify-between border-b border-border-default",
        processingStepIconWrapper: "flex-shrink-0 w-6 h-6 sm:w-8 sm:h-8 flex items-center justify-center",
        processingStepDone: "w-5 h-5 sm:w-6 sm:h-6 bg-background-success rounded-full flex items-center justify-center",
        processingStepDoneIcon: "text-text-success text-xs",
        processingStepActive: "w-5 h-5 sm:w-6 sm:h-6 bg-accent-default rounded-full animate-pulse",

        // Results screen
        resultsScreen: "h-screen flex flex-col",
        resultsHeader: "bg-background-primary/80 backdrop-blur-md border-b border-border-default sticky top-0 z-30 flex-shrink-0",
        resultsHeaderInner: "max-w-screen-xl mx-auto px-sm sm:px-md lg:px-lg py-sm sm:py-md",
        resultsHeaderRow: "flex flex-col lg:flex-row items-start lg:items-center justify-between gap-sm",
        resultsHeaderLeft: "flex items-center gap-sm sm:gap-lg",
        resultsBackBtn: "text-text-secondary flex gap-2 items-center leading-none hover:text-text-primary transition-colors text-para-sm",
        resultsHeaderRight: "flex items-center gap-xs sm:gap-sm",
        resultsPreviewBtn: "flex items-center gap-xs px-sm sm:px-md py-xs sm:py-sm rounded-lg bg-accent-default text-accent-foreground text-para-xs sm:text-para-sm font-medium hover:bg-accent-hover transition-colors",
        resultsToggleWrapper: "bg-background-secondary rounded-full p-0.5 sm:p-1 flex",
        resultsToggleBtnActive: "px-sm sm:px-md py-xs sm:py-sm rounded-full text-para-xs sm:text-para-sm font-medium transition-all bg-accent-default text-accent-foreground",
        resultsToggleBtnInactive: "px-sm sm:px-md py-xs sm:py-sm rounded-full text-para-xs sm:text-para-sm font-medium transition-all text-text-secondary hover:text-text-primary",
        resultsMain: "max-w-screen-xl mx-auto px-sm sm:px-md lg:px-lg w-full flex-grow overflow-hidden",
        resultsGrid: "grid grid-cols-1 lg:grid-cols-5 lg:gap-lg h-full",
        resultsAside: "hidden lg:block lg:col-span-2 h-full py-lg",
        resultsAsideInner: "sticky top-24 h-[calc(100vh-8rem)] flex flex-col gap-md",
        resultsTasteCard: "bg-background-secondary border border-border-default rounded-xl p-md",
        resultsTasteCardHeader: "flex items-center justify-between mb-sm",
        resultsTasteCardHeaderLeft: "flex items-center gap-sm",
        resultsTasteIconWrapper: "w-6 h-6 bg-accent-default rounded-full flex items-center justify-center",
        resultsTasteIconInner: "text-accent-foreground text-xs",
        resultsTasteClearBtn: "text-para-xs text-text-tertiary hover:text-accent-default transition-colors",
        resultsTasteBody: "space-y-xs",
        resultsTasteTag: "px-xs py-1 bg-accent-subtle dark:bg-transparent text-accent-default rounded text-para-xs",
        resultsChatWrapper: "flex-1 min-h-0",
        resultsSectionsCol: "lg:col-span-3 h-full overflow-y-auto custom-scrollbar py-lg",
        resultsSectionsInner: "flex flex-col gap-lg",
        resultsFeedbackComplete: "mt-lg text-center",
        resultsFeedbackCard: "bg-gradient-to-r from-accent-default to-accent-hover rounded-xl sm:rounded-2xl p-lg sm:p-xl text-accent-foreground max-w-2xl mx-auto",
        resultsFeedbackBtn: "bg-background-primary text-accent-default px-lg sm:px-xl py-sm sm:py-md rounded-lg sm:rounded-xl font-semibold hover:bg-background-secondary transition-colors",
        resultsMobileChatWrapper: "lg:hidden",
    },
    preview: {
        loadingWrapper: "flex items-center justify-center h-screen bg-background-primary",
        loadingText: "text-text-tertiary text-para-sm",
        errorWrapper: "flex items-center justify-center h-screen bg-background-primary",
        errorText: "text-text-tertiary text-para-sm"
    },
    onboarding: {
        loadingWrapper: "flex justify-center items-center min-h-[300px]",
        root: "relative min-h-screen flex bg-background-secondary transition-colors",
        inner: "flex-1 flex flex-col px-lg z-10",
        centerWrapper: "flex-1 flex items-center justify-center max-md:mb-md",
        card: "w-full max-w-3xl mx-auto bg-background-primary rounded-2xl px-lg md:px-xl py-lg shadow-xl transition-colors border border-border-default",
        logoHint: "text-para-sm text-text-tertiary mt-sm",
        selectionBtnBase: "transition-all",
        selectionBtnSelected: "border-accent-default bg-accent-subtle/20 text-accent-default",
        selectionBtnUnselected: "border-border-default hover:border-border-focus text-text-secondary",
        selectionBtnDisabled: "opacity-50 cursor-not-allowed",
        dropzoneBase: "relative border-2 border-dashed rounded-lg p-lg text-center transition-all",
        dropzoneActive: "border-accent-default bg-accent-subtle",
        dropzoneInactive: "border-border-muted hover:border-border-default",
    },
    intakeForm: {
        loadingWrapper: "flex justify-center items-center min-h-[300px]",
        root: "relative min-h-screen flex bg-background-secondary transition-colors",
        inner: "flex-1 flex flex-col z-10",
        centerWrapper: "flex-1 flex items-center justify-center px-lg max-md:mb-md",
        feedbackWrapper: "w-full max-w-lg mx-auto",
        card: "w-full max-w-3xl mx-auto bg-background-primary rounded-2xl px-lg md:px-xl py-lg shadow-xl transition-colors border border-border-default",
        selectionBtnBase: "transition-all",
        selectionBtnSelected: "border-accent-default bg-accent-subtle/20 text-accent-default",
        selectionBtnUnselected: "border-border-default hover:border-border-focus text-text-secondary",
        selectionBtnDisabled: "disabled:opacity-50",
        dropzoneBase: "relative border-2 border-dashed rounded-lg p-lg text-center transition-all",
        dropzoneActive: "border-accent-default bg-accent-subtle",
        dropzoneInactive: "border-border-muted hover:border-border-default",
    },
    onboardComplete: {
        root: "relative min-h-screen flex bg-background-secondary transition-colors overflow-hidden",
        inner: "flex-1 flex flex-col z-10",
        centerWrapper: "flex-1 flex items-center justify-center px-lg",
        card: "w-full max-w-3xl mx-auto relative",
        contentArea: "relative min-h-[500px] z-10 text-center flex flex-col items-center justify-start",
        iconWrapper: "w-24 h-24 bg-accent-subtle rounded-full flex items-center justify-center",
        contentReserved: "min-h-[100px] flex flex-col justify-start",
        buttonsRow: "min-h-[60px] flex items-center mt-lg lg:mt-none",
        buttonsInner: "flex flex-col sm:flex-row gap-sm justify-center items-center",
        motionStyle: { willChange: 'transform, opacity', transformOrigin: 'center' } as React.CSSProperties,
    }
} as const